name: Deploy mewcrazy/StripChat-Enhanced

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      # Step 1: Download waitForKeyElements.js
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Downloading waitForKeyElements.js
        run: build/build.sh

      # Step 2: Remove Google API Key from codebase
      - name: Remove Google API Key from codebase
        id: remove_api_keys
        run: sed -i -e 's/var googleApiKey = "${{ secrets.GOOGLE_TRANSLATION_APIKEY }}"/var googleApiKey = ""/g' deploy/stripchat-enhanced.script.js

      # Step 3: Check for any changes
      - name: Check for any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      # Step 4: Commit
      - name: Commit files
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.name mewcrazy
          git config --local user.email "kontakt@dennis-bitsch.de"      
          git fetch
          git add deploy/waitForKeyElements.min.js
          git add deploy/jquery.min.js
          git commit -am "Update repository files [skip ci]" 
          git push -f origin main

      # Push
      - name: Push to GitHub
        if: steps.verify_diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true